services:
  db:
      image: mariadb:10.5.12
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./data/mariadb:/var/lib/mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=mariadb
        - MYSQL_PASSWORD=mariadb
        - MARIADB_DATABASE=mariadb
        - MARIADB_USER=mariadb
      ports:
        - "3300:3306"
