# Generated by Django 4.0.2 on 2022-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="time",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(),
        ),
    ]
