# Generated by Django 4.0.2 on 2022-02-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0004_remove_appointment_time_alter_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("a", "Accept"), ("c", "Cancel"), ("f", "Finish")],
                default="a",
                max_length=15,
            ),
        ),
    ]
