# Generated by Django 4.0.2 on 2022-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_remove_appointment_category_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("a", "Accepted"), ("c", "Canceled"), ("f", "Finished")],
                default="a",
                max_length=15,
            ),
        ),
    ]
