# Generated by Django 4.0.2 on 2022-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_alter_comment_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
